### ISSUE TITLE
Issue with data format upload following MNE script 

### ISSUE THREAD

**Issue by beapdk** [brainhack-school2020/SNF_ADHDsubtypes_project#2]
Data import of .eeg files needs to be modified as script followed isn't adapted to that format.

**Comment by vborghe** [comment]
Which script were you following? Is this mne-python function the one you need/are using? https://mne.tools/stable/auto_tutorials/io/plot_20_reading_eeg_data.html#brainvision-vhdr-vmrk-eeg [another potentially useful example of loading here: https://mne.tools/mne-bids/stable/auto_examples/rename_brainvision_files.html#sphx-glr-auto-examples-rename-brainvision-files-py]
